roles:
- role: supervisor
  is_unique: true
- role: trustee
  is_unique: false
- role: clerk
  is_unique: true
- role: treasurer
  is_unique: true
  aliases:
  - township treasurer
- role: deputy clerk
  is_unique: true
- role: deputy treasurer
  is_unique: true
- role: assessor
  is_unique: true
  aliases:
  - township assessor
