roles:
- role: supervisor
  is_unique: true
  head_of_government: false
  aliases: []
- role: trustee
  is_unique: false
  head_of_government: false
  aliases: []
- role: clerk
  is_unique: true
  head_of_government: false
  aliases: []
- role: treasurer
  is_unique: true
  head_of_government: false
  aliases:
  - township treasurer
- role: deputy clerk
  is_unique: true
  head_of_government: false
  aliases: []
- role: deputy treasurer
  is_unique: true
  head_of_government: false
  aliases: []
- role: assessor
  is_unique: true
  head_of_government: false
  aliases:
  - township assessor
excluded_roles: []
