roles:
- role: mayor
  is_unique: true
  head_of_government: false
  aliases: []
- role: mayor pro tempore
  is_unique: true
  head_of_government: false
  aliases:
  - mayor protem
  - mayor protemp
  - mayor pro-tem
  - mayor pro-temp
  - mayor pro tem
  - mayor pro temp
  - mayor pro-tempore
  - mayor-pro tem
  - mayor protem
- role: assistant mayor
  is_unique: true
  head_of_government: false
  aliases: []
- role: deputy mayor
  is_unique: true
  head_of_government: false
  aliases: []
- role: vice mayor
  is_unique: true
  head_of_government: false
  aliases:
  - vice-mayor
- role: commission president
  is_unique: true
  head_of_government: false
  aliases:
  - commissioner president
- role: commissioner vice president
  is_unique: true
  head_of_government: false
  aliases:
  - commissioner vice-president
  - commissioner-vice president
  - commission vice-president
  - commission vice president
- role: commissioner
  is_unique: false
  head_of_government: false
  aliases:
  - city commissioner
- role: deputy mayor pro tempore
  is_unique: true
  head_of_government: false
  aliases:
  - deputy mayor pro tem
  - deputy mayor pro-tem
  - deputy mayor pro tempore
- role: council president
  is_unique: true
  head_of_government: false
  aliases:
  - president
  - city council president
  - council member president
  - president of the council
- role: council president pro tem
  is_unique: true
  head_of_government: false
  aliases:
  - council president pro-tem
  - council president pro tempore
- role: deputy council president
  is_unique: true
  head_of_government: false
  aliases: []
- role: council vice president
  is_unique: true
  head_of_government: false
  aliases:
  - vice president
  - vice-president
  - council vice-president
  - council member vice president
  - council member vice-president
- role: council manager
  is_unique: true
  head_of_government: false
  aliases: []
- role: council member
  is_unique: false
  head_of_government: false
  aliases:
  - council-member
  - city councilor
  - town councilor
  - council member at-large
  - councilperson
  - councilmember
  - councilmembers
  - councilwoman
  - councilman
  - councilor
  - councillor
  - city councilman
  - city councilwoman
  - city councilmember
  - city council member
  - city council
  - town council representative
  - town council member
  - town councilmember
  - town council
  - town board member
  - representative
  - council
  - member
  - councilmen
  - councilwomen
  - council members
- role: committee member
  is_unique: false
  head_of_government: false
  aliases:
  - township committee member
  - committeeman
  - committeewoman
- role: select board chair
  is_unique: false
  head_of_government: false
  aliases:
  - selectboard chairman
  - selectboard chairwoman
  - select board chairman
  - select board chairwoman
  - selectboard chair
- role: select board vice chair
  is_unique: true
  head_of_government: false
  aliases:
  - select board vice chairman
  - select board vice chairwoman
  - select board vice-chair
  - select board vice-chairman
  - select board vice-chairwoman
  - selectboard vice chair
  - selectboard vice chairman
  - selectboard vice chairwoman
  - selectboard vice-chair
  - selectboard vice-chairman
  - selectboard vice-chairwoman
- role: select board member
  is_unique: false
  head_of_government: false
  aliases:
  - selectmen
  - selectman
  - selectwoman
  - select board
  - board of selectmen
  - board of selectmen member
  - select board representative
  - selectboard
  - selectboard member
  - select board member
- role: president board of aldermen
  is_unique: true
  head_of_government: false
  aliases: []
- role: vice president board of aldermen
  is_unique: true
  head_of_government: false
  aliases: []
- role: alderperson
  is_unique: false
  head_of_government: false
  aliases:
  - alder
  - alderman
  - aldermen
  - alderwoman
  - city alderman
  - city alderwoman
  - city council alderman
  - city council alderwoman
- role: chair
  is_unique: false
  head_of_government: false
  aliases:
  - council chair
  - council chairman
  - council chairwoman
  - chairman
  - chairwoman
  - town council chair
- role: vice chair
  is_unique: false
  head_of_government: false
  aliases:
  - council vice chair
  - council vice chairman
  - council vice chairwoman
  - council vice-chair
  - council vice-chairman
  - council vice-chairwoman
  - vice-chair
  - vice-chairman
  - vice-chairwoman
  - vice chairman
  - vice chairwoman
  - vice-chairman
  - vice-chairwoman
- role: chair pro tem
  is_unique: false
  head_of_government: false
  aliases: []
excluded_roles:
- city manager
- city administrator
- city attorney
- municipal attorney
- city secretary
- city solicitor
- town attorney
- town manager
- village attorney
- village manager
