#!/usr/bin/env python3
"""
Compare every county and local jurisdiction in data_source/ with the OCD division
registry and write the disagreements to data_source/ocdid_mismatches.yml:

  rule_mismatches    — the registry knows the GEOID, but our minting rules
                       (scripts/ocdids/mint.py) produce a different ID. `via: alias`
                       marks registry.GEOID_ALIASES, which the rules can't reach by design.
  matched_by_id_only — the registry doesn't know the GEOID, but the minted ID is in it
                       (e.g. a MA town that became a city and got a new GEOID). Check each
                       is the same jurisdiction, not a coincidence of names.
  not_in_registry    — neither the GEOID nor the minted ID is in the registry.
  collisions         — minted IDs that still collide after the registry's fallback.

Usage:
    uv run python -m scripts.ocdids.registry_report
"""

import io
from enum import Enum
from typing import Dict, List, Mapping, Optional, Tuple

from ruamel.yaml.comments import CommentedMap

from scripts.jurisdictions.yaml_io import ryaml
from scripts.ocdids.assign import assign
from scripts.ocdids.models import Assignment, Registry, Source
from scripts.ocdids.registry import GEOID_ALIASES, load_registry
from scripts.ocdids.stored import StoredJurisdiction, read_state, stored_by_geoid, stored_states
from scripts.paths import PROJECT_ROOT

REPORT_PATH = PROJECT_ROOT / "data_source" / "ocdid_mismatches.yml"
_HEADER = (
    "AUTO-GENERATED by scripts/ocdids/registry_report.py — do not edit by hand.\n"
    "Every county/local jurisdiction whose OCD-ID the registry (opencivicdata/ocd-division-ids)\n"
    "doesn't confirm. See the script's docstring for what each section means."
)


class Section(str, Enum):
    RULE_MISMATCHES = "rule_mismatches"
    MATCHED_BY_ID_ONLY = "matched_by_id_only"
    NOT_IN_REGISTRY = "not_in_registry"
    COLLISIONS = "collisions"


Report = Dict[str, Dict[str, List[dict]]]
StateAssignments = Tuple[List[StoredJurisdiction], Dict[str, Assignment]]


def section_for(assignment: Assignment, registry: Registry) -> Optional[Section]:
    if assignment.source == Source.REGISTRY:
        return Section.RULE_MISMATCHES if assignment.minted_ocdid != assignment.division_ocdid else None
    if assignment.division_ocdid in registry.division_ocdids:
        return Section.MATCHED_BY_ID_ONLY
    return Section.NOT_IN_REGISTRY


def report_row(section: Section, assignment: Assignment, name: str) -> dict:
    row = {"geoid": assignment.geoid, "name": name}
    if section == Section.RULE_MISMATCHES:
        row["registry"] = assignment.division_ocdid
        row["minted"] = assignment.minted_ocdid
        if assignment.geoid in GEOID_ALIASES:
            row["via"] = "alias"
    elif section == Section.COLLISIONS:
        row["ocdid"] = assignment.division_ocdid
    else:
        row["minted"] = assignment.division_ocdid
    return row


def state_rows(
    stored: List[StoredJurisdiction], assignments: Mapping[str, Assignment], registry: Registry
) -> List[Tuple[Section, dict]]:
    """(section, row) pairs for one state, ordered by OCD-ID."""
    names = {geoid: j.name for geoid, j in stored_by_geoid(stored).items()}
    rows = []
    for assignment in sorted(assignments.values(), key=lambda a: a.division_ocdid):
        name = names[assignment.geoid]
        section = section_for(assignment, registry)
        if section is not None:
            rows.append((section, report_row(section, assignment, name)))
        if assignment.collision:
            rows.append((Section.COLLISIONS, report_row(Section.COLLISIONS, assignment, name)))
    return rows


def build_report(by_state: Mapping[str, StateAssignments], registry: Registry) -> Report:
    report: Report = {section.value: {} for section in Section}
    for state, (stored, assignments) in by_state.items():
        for section, row in state_rows(stored, assignments, registry):
            report[section.value].setdefault(state, []).append(row)
    return report


def render_report(report: Report) -> str:
    document = CommentedMap(report)
    document.yaml_set_start_comment(_HEADER)
    out = io.StringIO()
    ryaml.dump(document, out)
    return out.getvalue()


def assign_state(state: str, registry: Registry) -> StateAssignments:
    stored, rows = read_state(state)
    return stored, assign(rows, registry.division_ocdid_by_geoid)


def current_report() -> str:
    registry = load_registry()
    return render_report(build_report({s: assign_state(s, registry) for s in stored_states()}, registry))


def main() -> None:
    REPORT_PATH.write_text(current_report())
    print(f"Wrote {REPORT_PATH.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    main()
