"""Header comments written to the top of each `data_source/**/jurisdictions.yml`.

Centralised because the three generators (states.py, counties.py, local.py) previously
each carried their own hardcoded copy, which drifted: the county header advertised a
`url` field for months while nothing populated it.

Each header documents both the *fields* and the *provenance* — the exact API calls,
Census text files, and local artifacts a given file is built from — so the file can be
regenerated or spot-checked by hand. API calls are rendered as curl commands
referencing `$CENSUS_API_KEY` so the key itself never lands in committed data.
"""

import textwrap

ACS_URL = "https://api.census.gov/data/2024/acs/acs5"
GAZ_URL = "https://www2.census.gov/geo/docs/maps-data/data/gazetteer/2025_Gazetteer"
TIGER_URL = "https://www2.census.gov/geo/tiger/TIGER2025"
WIKI_URL = "https://en.wikipedia.org/wiki"

# Census `for=` value → the gazetteer file that supplies its GEOIDs and funcstat
_GAZ_FILES = {
    "places": "2025_gaz_place_{fips}.txt",
    "county_subdivisions": "2025_gaz_cousubs_{fips}.txt",
}
_API_FOR = {
    "places": "place:*",
    "county_subdivisions": "county%20subdivision:*",
}


def _curl(query: str) -> str:
    return f'curl "{ACS_URL}?{query}&key=$CENSUS_API_KEY"'


def _block(title: str, lines: list[str]) -> str:
    return f"{title}\n" + "".join(f"    {line}\n" for line in lines)


# One description per field. Shared across levels so wording cannot drift between the
# three headers; a level overrides an entry only where its meaning genuinely differs
# (e.g. `geoid` is 2 digits for a state, 5 for a county).
FIELD_DOCS = {
    "name": "Common name as returned by Census; updated each run.",
    "url": "Official government website (from the Wikipedia infobox); only written "
           "if absent — existing values are never overwritten by scripts.",
    "wiki_url": "Wikipedia page URL for this jurisdiction.",
    "population": "ACS 5-year population estimate; updated on every run.",
    "status": "Lifecycle: absent = active, 'inactive' = dropped from census.",
    "generated_comments": "Script-generated notes (e.g. wiki URL candidates). "
                          "Replaced each run.",
    "comments": "Free-form human notes; NEVER overwritten by scripts.",
}

_WRAP_AT = 96


def _fields(*names_and_overrides: str, **overrides: str) -> str:
    """Render an aligned field-documentation block.

    Column width and continuation indents are computed, not hand-maintained — the old
    hand-aligned blocks had already drifted apart between the county and local headers.
    """
    # {**defaults, **overrides} rather than .get(n, FIELD_DOCS[n]): the latter evaluates
    # FIELD_DOCS[n] eagerly and raises for override-only fields (id, issues, warnings).
    docs = {**FIELD_DOCS, **overrides}
    width = max(len(n) for n in names_and_overrides)
    out = []
    for name in names_and_overrides:
        desc = docs[name]
        label = f"  {name.ljust(width)} - "
        # Never split on hyphens or inside long tokens — OCD-IDs and URLs must stay
        # readable and copy-pasteable out of the generated comment.
        body = textwrap.wrap(
            desc,
            width=_WRAP_AT - len(label),
            break_on_hyphens=False,
            break_long_words=False,
        ) or [""]
        out.append(label + body[0])
        out.extend(" " * len(label) + line for line in body[1:])
    return "\n".join(out) + "\n"


def state_header(state: str, fips: str) -> str:
    return (
        "AUTO-GENERATED by scripts/jurisdictions/states.py — safe to re-run.\n"
        "\n"
        "Fields:\n"
        + _fields(
            "id", "name", "url", "population", "geoid", "comments",
            id="OCD-ID: ocd-jurisdiction/country:us/state:{state}/government; stable — "
               "never regenerated.",
            name="State name as returned by Census ACS; updated each run.",
            geoid="2-digit Census FIPS code for the state.",
        )
        + "\n"
        "Sources:\n"
        + _block("  name, population — Census ACS 5-year:", [
            _curl(f"get=NAME,B01003_001E&for=state:{fips}"),
        ])
        + _block("  Boundary geometry (national file, filtered to STATEFP):", [
            f"{TIGER_URL}/STATE/tl_2025_us_state.zip",
        ])
        + _block("  Generated artifacts:", [
            f"data/.maps/{state}/state.geojson",
        ])
    )


def county_header(state: str, fips: str, state_name: str) -> str:
    wiki_page = f"List_of_counties_in_{state_name.replace(' ', '_')}"
    return (
        "AUTO-GENERATED by scripts/jurisdictions/counties.py — safe to re-run, comments and manual edits are preserved.\n"
        "\n"
        "Fields per county:\n"
        + _fields(
            "id", "name", "url", "wiki_url", "population", "geoid", "status",
            "issues", "generated_comments", "comments", "warnings",
            id="OCD-ID: ocd-jurisdiction/country:us/state:{state}/county:{name}/government; "
               "stable once assigned — preserved via GEOID matching if Census name changes.",
            name="Common name including type suffix (e.g. 'King County'); updated each run.",
            wiki_url="Wikipedia page URL for this county.",
            geoid="Census FIPS GEOID (state + county, 5 digits); stable identifier.",
            status="Lifecycle: absent = active, 'inactive' = dropped from census. NOTE: not "
                   "yet written by scripts/jurisdictions/counties.py.",
            issues="Per-county problems: no_wiki_match, geoid_mismatch, no_official_url. "
                   "Replaced on every run.",
            warnings="Root-level: warnings not tied to a specific county.",
        )
        + "\n"
        "Sources:\n"
        + _block("  name, population — Census ACS 5-year:", [
            _curl(f"get=NAME,B01003_001E&for=county:*&in=state:{fips}"),
        ])
        + _block("  url, wiki_url — Wikipedia list page (county name in column 0,\n"
                 "  3-digit FIPS in column 1; the infobox supplies only the website):", [
            f"{WIKI_URL}/{wiki_page}",
        ])
        + _block("  Boundary geometry (national file, filtered to STATEFP):", [
            f"{TIGER_URL}/COUNTY/tl_2025_us_county.zip",
        ])
        + _block("  Generated artifacts:", [
            f"scripts/jurisdictions/scrapers/cache/{state}_counties_wikipedia.json  (cached infobox scrapes)",
            f"data/.maps/{state}/counties.geojson",
        ])
    )


def local_header(state: str, fips: str, state_name: str, pull_from_census: list[str]) -> str:
    wiki_page = f"List_of_municipalities_in_{state_name.replace(' ', '_')}"

    acs_calls = [
        _curl(f"get=NAME,B01003_001E&for={_API_FOR[src]}&in=state:{fips}")
        for src in pull_from_census
    ]
    gaz_files = [
        f"{GAZ_URL}/{_GAZ_FILES[src].format(fips=fips)}"
        for src in pull_from_census
    ]
    tiger_files = []
    if "places" in pull_from_census:
        tiger_files.append(f"{TIGER_URL}/PLACE/tl_2025_{fips}_place.zip")
    if "county_subdivisions" in pull_from_census:
        tiger_files.append(f"{TIGER_URL}/COUSUB/tl_2025_{fips}_cousub.zip")

    return (
        "AUTO-GENERATED by scripts/jurisdictions/local.py — safe to re-run, comments and manual edits are preserved.\n"
        "\n"
        "Fields per jurisdiction:\n"
        + _fields(
            "id", "name", "url", "wiki_url", "population", "geoid", "status",
            "issues", "generated_comments", "comments", "warnings",
            id="OCD-ID for the jurisdiction; stable once assigned — preserved across runs via "
               "GEOID matching even if the Census name changes.",
            name="Common name including LSAD suffix (e.g. 'Newark city'); updated each run.",
            geoid="Census FIPS GEOID; stable identifier used to match jurisdictions across "
                  "runs — never changes for an incorporated place.",
            issues="Per-jurisdiction problems: ocdid_collision, no_wiki_match, geoid_mismatch. "
                   "Replaced on every run.",
            warnings="Root-level: warnings not tied to a specific jurisdiction.",
        )
        + "\n"
        f"Census sources for this state: {', '.join(pull_from_census)}\n"
        "\n"
        "Sources:\n"
        + _block("  name, population — Census ACS 5-year:", acs_calls)
        + _block("  geoid, funcstat — Census Gazetteer (tab-separated; funcstat filtered\n"
                 "  to A/B/C/G, zero-population entries skipped):", gaz_files)
        + _block("  url, wiki_url — Wikipedia list page:", [f"{WIKI_URL}/{wiki_page}"])
        + _block("  Boundary geometry:", tiger_files)
        + _block("  Generated artifacts:", [
            f"scripts/jurisdictions/scrapers/cache/{state}_wikipedia.json  (cached infobox scrapes)",
            f"data/.maps/{state}/local.geojson",
            f"data_source/{state}/counties/jurisdictions.yml  (county OCD-IDs for the spatial join)",
            f"data_source/{state}/local/validation/  (external comparison sources)",
        ])
    )
