government_forms:
  commission:
    organizations:
      - {name: Levy Court, role_labels: [Commissioner, Commission President]}
  council_manager:
    organizations:
      - {name: County Council, role_labels: [Council Member, Council President]}
  county_executive:
    organizations:
      - {name: County Council, role_labels: [Council Member, Council President]}
      - {name: County Executive, role_labels: [County Executive]}
