roles:
- id: mayor
  label: Mayor
  is_unique: true
- id: county-executive
  label: County Executive
  is_unique: true
- id: commission-president
  label: Commission President
  is_unique: true
  aliases:
  - commissioner president
- id: deputy-mayor
  label: Deputy Mayor
  is_unique: true
- id: alderperson
  label: Alderperson
  is_unique: false
  aliases:
  - alder
  - alderman
  - aldermen
  - alderwoman
  - city alderman
  - city alderwoman
  - city council alderman
  - city council alderwoman
- id: vice-mayor
  label: Vice Mayor
  is_unique: true
  aliases:
  - vice-mayor
- id: assistant-mayor
  label: Assistant Mayor
  is_unique: true
- id: mayor-pro-tempore
  label: Mayor Pro Tempore
  is_unique: true
  aliases:
  - mayor pro tem
  - mayor pro temp
  - mayor pro-tem
  - mayor pro-temp
  - mayor pro-tempore
  - mayor protem
  - mayor protemp
  - mayor-pro tem
- id: deputy-mayor-pro-tempore
  label: Deputy Mayor Pro Tempore
  is_unique: true
  aliases:
  - deputy mayor pro tem
  - deputy mayor pro tempore
  - deputy mayor pro-tem
- id: council-president
  label: Council President
  is_unique: true
  aliases:
  - city council president
  - council member president
  - president
  - president of the council
- id: council-vice-president
  label: Council Vice President
  is_unique: true
  aliases:
  - council member vice president
  - council member vice-president
  - council vice-president
  - vice president
  - vice-president
- id: council-president-pro-tem
  label: Council President Pro Tem
  is_unique: true
  aliases:
  - council president pro tempore
  - council president pro-tem
- id: deputy-council-president
  label: Deputy Council President
  is_unique: true
- id: president-pro-tempore
  label: President Pro Tempore
  is_unique: true
  aliases:
  - president pro tem
- id: select-board-member
  label: Select Board Member
  is_unique: false
  aliases:
  - Select Person
  - Selectperson
  - board of selectmen
  - board of selectmen member
  - select board
  - select board member
  - select board representative
  - selectboard
  - selectboard member
  - selectman
  - selectmen
  - selectwoman
- id: town-meeting-member
  label: Town Meeting Member
  is_unique: false
- id: chair
  label: Chair
  is_unique: true
  aliases:
  - Chairperson
  - chairman
  - chairwoman
  - council chair
  - council chairman
  - council chairwoman
  - town council chair
- id: vice-chair
  label: Vice Chair
  is_unique: true
  aliases:
  - Vice Chairperson
  - Vice-Chairperson
  - council vice chair
  - council vice chairman
  - council vice chairwoman
  - council vice-chair
  - council vice-chairman
  - council vice-chairwoman
  - vice chairman
  - vice chairwoman
  - vice-chair
  - vice-chairman
  - vice-chairwoman
- id: commissioner-vice-president
  label: Commissioner Vice President
  is_unique: true
  aliases:
  - commission vice president
  - commission vice-president
  - commissioner vice-president
  - commissioner-vice president
- id: chair-pro-tem
  label: Chair Pro Tem
  is_unique: true
- id: council-member
  label: Council Member
  is_unique: false
  aliases:
  - city council
  - city council member
  - city councilman
  - city councilmember
  - city councilor
  - city councilwoman
  - council
  - council at large
  - council member at-large
  - council members
  - council person
  - council-member
  - councillor
  - councilman
  - councilman-at-large
  - councilmember
  - councilmembers
  - councilmen
  - councilor
  - councilperson
  - councilperson at-large
  - councilwoman
  - councilwoman at large
  - councilwoman-at-large
  - councilwomen
  - member
  - representative
  - town board member
  - town council
  - town council member
  - town council representative
  - town councilmember
  - town councilor
- id: commissioner
  label: Commissioner
  is_unique: false
  aliases:
  - city commissioner
- id: committee-member
  label: Committee Member
  is_unique: false
  aliases:
  - Committee Woman
  - Committeeperson
  - Committeewomen
  - committee person
  - committeeman
  - committeewoman
  - township committee member
- id: trustee
  label: Trustee
  is_unique: false
  aliases:
  - Township Trustee
  - Trustees
  - Village Trustee
- id: supervisor
  label: Supervisor
  is_unique: false
  aliases:
  - Board of Supervisors
  - Town Supervisor
  - Township Supervisor
- id: deputy-supervisor
  label: Deputy Supervisor
  is_unique: true
- id: council-manager
  label: Council Manager
  is_unique: true
  aliases:
  - Township Manager
- id: clerk
  label: Clerk
  is_unique: true
  aliases:
  - Borough Clerk
  - City Clerk
  - Municipal Clerk
  - Town Clerk
  - Township Clerk
  - Village Clerk
- id: deputy-clerk
  label: Deputy Clerk
  is_unique: true
  aliases:
  - Deputy City Clerk
  - Deputy Town Clerk
  - Deputy Township Clerk
- id: treasurer
  label: Treasurer
  is_unique: true
  aliases:
  - City Treasurer
  - Town Treasurer
  - Township Treasurer
  - Village Treasurer
- id: deputy-treasurer
  label: Deputy Treasurer
  is_unique: true
  aliases:
  - Deputy City Treasurer
  - Deputy Township Treasurer
- id: moderator
  label: Moderator
  is_unique: true
  aliases:
  - Town Moderator
- id: secretary
  label: Secretary
  is_unique: true
  aliases:
  - Town Secretary
- id: assessor
  label: Assessor
  is_unique: false
  aliases:
  - City Assessor
  - Township Assessor
- id: city-attorney
  label: City Attorney
  is_unique: true
  aliases:
  - city solicitor
  - municipal attorney
  - town attorney
  - village attorney
- id: city-manager
  label: City Manager
  is_unique: true
  aliases:
  - city administrator
  - town manager
  - village manager
- id: city-secretary
  label: City Secretary
  is_unique: true
