import os
import sys
from pathlib import Path

import requests

from schemas import Jurisdiction
from scripts.state_configs import state_configs
from scripts.maps.county import build_county_map_for_state
from scripts.setup_local import _load_existing_jurisdictions, get_names, ryaml

PROJECT_ROOT = Path(__file__).parent.parent
_ACS_URL = "https://api.census.gov/data/2024/acs/acs5"


def _acs_url(query: str) -> str:
    key = os.environ.get("CENSUS_API_KEY")
    if not key:
        sys.exit(
            "CENSUS_API_KEY env var is required. "
            "Sign up: https://api.census.gov/data/key_signup.html — add to .env"
        )
    return f"{_ACS_URL}?{query}&key={key}"


def pull_county_jurisdiction_data(state: str):
    """Fetch county jurisdictions from Census ACS and write to data_source/{state}/counties/jurisdictions.yml."""
    state_config = state_configs.get(state.lower())
    fips = state_config["fips"]

    output_path = PROJECT_ROOT / "data_source" / state / "counties" / "jurisdictions.yml"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    doc, existing_by_id = _load_existing_jurisdictions(output_path)

    api_url = _acs_url(f"get=NAME,B01003_001E&for=county:*&in=state:{fips}")
    response = requests.get(api_url)
    if response.status_code != 200:
        print(f"Census county API request failed for {state}: {response.status_code}")
        return

    existing_by_geoid = {
        j["geoid"]: ocdid
        for ocdid, j in existing_by_id.items()
        if j.get("geoid")
    }

    all_jurisdictions_map = dict(existing_by_id)
    for row in response.json()[1:]:
        name = row[0]           # e.g. "King County, Washington"
        population = int(row[1])
        county_code = row[3]    # 3-digit county FIPS
        geoid = f"{fips}{county_code}"

        if population == 0:
            continue

        county_name, friendly_name = get_names(name)
        ocdid = f"ocd-jurisdiction/country:us/state:{state}/county:{county_name}/government"

        old_ocdid = existing_by_geoid.get(geoid)
        if old_ocdid:
            all_jurisdictions_map[old_ocdid]["population"] = population
            all_jurisdictions_map[old_ocdid]["name"] = friendly_name
        else:
            all_jurisdictions_map[ocdid] = Jurisdiction(
                id=ocdid, name=friendly_name, population=population, geoid=geoid
            ).model_dump(exclude_none=True)

    sorted_jurisdictions = sorted(
        all_jurisdictions_map.values(),
        key=lambda j: j.get("population") or 0,
        reverse=True,
    )
    doc["jurisdictions"] = sorted_jurisdictions

    doc.yaml_set_start_comment(
        "AUTO-GENERATED by setup_counties.py — safe to re-run.\n"
        "\n"
        "Fields per county:\n"
        "  id         - OCD-ID: ocd-jurisdiction/country:us/state:{state}/county:{name}/government;\n"
        "               stable once assigned — preserved via GEOID matching if Census name changes.\n"
        "  name       - Common name including type suffix (e.g. 'King County'); updated each run.\n"
        "  url        - Official government website; only written if absent — never overwritten.\n"
        "  population - ACS 5-year population estimate; updated on every run.\n"
        "  geoid      - Census FIPS GEOID (state + county, 5 digits); stable identifier.\n"
        "  status     - Lifecycle: absent = active, 'inactive' = dropped from census.\n"
        "  comments   - Free-form human notes; NEVER overwritten by scripts.\n"
    )

    with open(output_path, "w") as f:
        ryaml.dump(doc, f)
    print(f"Written {len(sorted_jurisdictions)} counties to {output_path}")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("state", nargs="?", help="State code (omit to run all states with counties enabled)")
    args = parser.parse_args()

    if args.state:
        if args.state not in state_configs:
            print(f"Unknown state '{args.state}'. Known states: {', '.join(state_configs)}")
            sys.exit(1)
        states = [args.state]
    else:
        states = list(state_configs.keys())
        print(f"Running for all states: {', '.join(states)}")

    for state in states:
        pull_county_jurisdiction_data(state)
        build_county_map_for_state(state, state_configs[state]["fips"])
