import sys
from pathlib import Path

import requests

from schemas import Jurisdiction
from scripts.state_configs import state_configs
from scripts.maps.state import build_state_map_for_state
from scripts.setup_local import _load_existing_jurisdictions, ryaml

PROJECT_ROOT = Path(__file__).parent.parent
_ACS_URL = "https://api.census.gov/data/2024/acs/acs5"


def pull_state_jurisdiction_data(state: str):
    """Fetch state jurisdiction from Census ACS and write to data_source/{state}/state/jurisdictions.yml."""
    state_config = state_configs.get(state.lower())
    fips = state_config["fips"]

    output_path = PROJECT_ROOT / "data_source" / state / "state" / "jurisdictions.yml"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    doc, existing_by_id = _load_existing_jurisdictions(output_path)

    api_url = f"{_ACS_URL}?get=NAME,B01003_001E&for=state:{fips}"
    response = requests.get(api_url)
    if response.status_code != 200:
        print(f"Census state API request failed for {state}: {response.status_code}")
        return

    row = response.json()[1]        # only one row — the state itself
    name = row[0]                   # e.g. "Washington"
    population = int(row[1])
    geoid = fips                    # state GEOID is the 2-digit FIPS

    ocdid = f"ocd-jurisdiction/country:us/state:{state}/government"

    existing_entry = existing_by_id.get(ocdid)
    if existing_entry:
        existing_entry["population"] = population
        existing_entry["name"] = name
        all_jurisdictions = list(existing_by_id.values())
    else:
        all_jurisdictions = [
            Jurisdiction(id=ocdid, name=name, population=population, geoid=geoid)
            .model_dump(exclude_none=True)
        ]

    doc["jurisdictions"] = all_jurisdictions

    doc.yaml_set_start_comment(
        "AUTO-GENERATED by setup_states.py — safe to re-run.\n"
        "\n"
        "Fields:\n"
        "  id         - OCD-ID: ocd-jurisdiction/country:us/state:{state}/government;\n"
        "               stable — never regenerated.\n"
        "  name       - State name as returned by Census ACS; updated each run.\n"
        "  url        - Official state government website; only written if absent — never overwritten.\n"
        "  population - ACS 5-year population estimate; updated on every run.\n"
        "  geoid      - 2-digit Census FIPS code for the state.\n"
        "  comments   - Free-form human notes; NEVER overwritten by scripts.\n"
    )

    with open(output_path, "w") as f:
        ryaml.dump(doc, f)
    print(f"Written state jurisdiction to {output_path}")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("state", nargs="?", help="State code (omit to run all states)")
    args = parser.parse_args()

    states = [args.state] if args.state else list(state_configs.keys())

    if args.state and args.state not in state_configs:
        print(f"Unknown state '{args.state}'. Known states: {', '.join(state_configs)}")
        sys.exit(1)

    if not args.state:
        print(f"Running for all states: {', '.join(states)}")

    for state in states:
        pull_state_jurisdiction_data(state)
        build_state_map_for_state(state, state_configs[state]["fips"])
