government_forms:
  commission:
    organizations:
      - {name: Board of Commissioners, role_labels: [Commissioner, Chair, Vice Chair]}
  county_executive:
    organizations:
      - {name: Board of Commissioners, role_labels: [Commissioner, Chair, Vice Chair]}
      - {name: County Executive, role_labels: [County Executive]}
