name: "[manual] Sync data back to crudder"
on:
  workflow_dispatch:

jobs:
  sync-with-api:
    environment: env-${{ github.actor }}
    runs-on: ubuntu-latest
    steps:
      - name: Call od_sync
        env:
          SERVICE_API_KEY: ${{ secrets.SERVICE_API_KEY }}
          API_CIVICPATCH_ORG_URL: ${{ vars.API_CIVICPATCH_ORG_URL }}
        run: |
          curl -X POST "$API_CIVICPATCH_ORG_URL/api/admin/od_sync" \
            -H "Content-Type: application/json" \
            -H "Authorization: $SERVICE_API_KEY" \
            --fail-with-body
